--------------------------------------------------------
--  File created - Sunday-December-10-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUK
--------------------------------------------------------

  CREATE TABLE "FPM"."PRODUK" 
   (	"NO_PRODUK" NUMBER(10,0), 
	"NAMA_PRODUK" VARCHAR2(50 BYTE), 
	"KATEGORI_PRODUK" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FPM" ;
--------------------------------------------------------
--  DDL for Table PELANGGAN
--------------------------------------------------------

  CREATE TABLE "FPM"."PELANGGAN" 
   (	"NO_PELANGGAN" NUMBER(10,0), 
	"NAMA_PELANGGAN" VARCHAR2(50 BYTE), 
	"ALAMAT_PELANGGAN" VARCHAR2(200 BYTE), 
	"KOTA_PELANGGAN" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FPM" ;
--------------------------------------------------------
--  DDL for Table PENJUALAN
--------------------------------------------------------

  CREATE TABLE "FPM"."PENJUALAN" 
   (	"NO_PRODUK" NUMBER(10,0), 
	"NO_PELANGGAN" NUMBER(10,0), 
	"NO_WAKTU" NUMBER(10,0), 
	"JUMLAH_PENJUALAN" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FPM" ;
--------------------------------------------------------
--  DDL for Table WAKTU
--------------------------------------------------------

  CREATE TABLE "FPM"."WAKTU" 
   (	"NO_WAKTU" NUMBER(10,0), 
	"TANGGAL" DATE, 
	"HARI" NUMBER(2,0), 
	"BULAN" NUMBER(2,0), 
	"TAHUN" NUMBER(4,0), 
	"QUARTER" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FPM" ;
REM INSERTING into FPM.PRODUK
SET DEFINE OFF;
REM INSERTING into FPM.PELANGGAN
SET DEFINE OFF;
REM INSERTING into FPM.PENJUALAN
SET DEFINE OFF;
REM INSERTING into FPM.WAKTU
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PRODUK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FPM"."PRODUK_PK" ON "FPM"."PRODUK" ("NO_PRODUK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FPM" ;
--------------------------------------------------------
--  DDL for Index PELANGGAN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FPM"."PELANGGAN_PK" ON "FPM"."PELANGGAN" ("NO_PELANGGAN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FPM" ;
--------------------------------------------------------
--  DDL for Index WAKTU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FPM"."WAKTU_PK" ON "FPM"."WAKTU" ("NO_WAKTU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FPM" ;
--------------------------------------------------------
--  Constraints for Table PRODUK
--------------------------------------------------------

  ALTER TABLE "FPM"."PRODUK" ADD CONSTRAINT "PRODUK_PK" PRIMARY KEY ("NO_PRODUK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FPM"  ENABLE;
  ALTER TABLE "FPM"."PRODUK" MODIFY ("KATEGORI_PRODUK" NOT NULL ENABLE);
  ALTER TABLE "FPM"."PRODUK" MODIFY ("NAMA_PRODUK" NOT NULL ENABLE);
  ALTER TABLE "FPM"."PRODUK" MODIFY ("NO_PRODUK" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PELANGGAN
--------------------------------------------------------

  ALTER TABLE "FPM"."PELANGGAN" ADD CONSTRAINT "PELANGGAN_PK" PRIMARY KEY ("NO_PELANGGAN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FPM"  ENABLE;
  ALTER TABLE "FPM"."PELANGGAN" MODIFY ("KOTA_PELANGGAN" NOT NULL ENABLE);
  ALTER TABLE "FPM"."PELANGGAN" MODIFY ("ALAMAT_PELANGGAN" NOT NULL ENABLE);
  ALTER TABLE "FPM"."PELANGGAN" MODIFY ("NAMA_PELANGGAN" NOT NULL ENABLE);
  ALTER TABLE "FPM"."PELANGGAN" MODIFY ("NO_PELANGGAN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PENJUALAN
--------------------------------------------------------

  ALTER TABLE "FPM"."PENJUALAN" MODIFY ("JUMLAH_PENJUALAN" NOT NULL ENABLE);
  ALTER TABLE "FPM"."PENJUALAN" MODIFY ("NO_WAKTU" NOT NULL ENABLE);
  ALTER TABLE "FPM"."PENJUALAN" MODIFY ("NO_PELANGGAN" NOT NULL ENABLE);
  ALTER TABLE "FPM"."PENJUALAN" MODIFY ("NO_PRODUK" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table WAKTU
--------------------------------------------------------

  ALTER TABLE "FPM"."WAKTU" ADD CONSTRAINT "WAKTU_PK" PRIMARY KEY ("NO_WAKTU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FPM"  ENABLE;
  ALTER TABLE "FPM"."WAKTU" MODIFY ("QUARTER" NOT NULL ENABLE);
  ALTER TABLE "FPM"."WAKTU" MODIFY ("TAHUN" NOT NULL ENABLE);
  ALTER TABLE "FPM"."WAKTU" MODIFY ("BULAN" NOT NULL ENABLE);
  ALTER TABLE "FPM"."WAKTU" MODIFY ("HARI" NOT NULL ENABLE);
  ALTER TABLE "FPM"."WAKTU" MODIFY ("TANGGAL" NOT NULL ENABLE);
  ALTER TABLE "FPM"."WAKTU" MODIFY ("NO_WAKTU" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PENJUALAN
--------------------------------------------------------

  ALTER TABLE "FPM"."PENJUALAN" ADD CONSTRAINT "PELANGGAN_FK" FOREIGN KEY ("NO_PELANGGAN")
	  REFERENCES "FPM"."PELANGGAN" ("NO_PELANGGAN") ENABLE;
  ALTER TABLE "FPM"."PENJUALAN" ADD CONSTRAINT "PRODUK_FK" FOREIGN KEY ("NO_PRODUK")
	  REFERENCES "FPM"."PRODUK" ("NO_PRODUK") ENABLE;
  ALTER TABLE "FPM"."PENJUALAN" ADD CONSTRAINT "WAKTU_FK" FOREIGN KEY ("NO_WAKTU")
	  REFERENCES "FPM"."WAKTU" ("NO_WAKTU") ENABLE;
