CREATE SEQUENCE  "FPM"."WAKTU_NEW_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 2081 CACHE 20 NOORDER  NOCYCLE ;

INSERT INTO WAKTU_NEW (ID_WAKTU, WAKTU) 
SELECT WAKTU_NEW_SEQ.nextval, s.*
FROM (SELECT distinct TIME_ID FROM SALES ORDER BY TIME_ID ASC) s;

select max(id_waktu) from waktu_new;

INSERT INTO SALES_NEW ( PROD_ID, CUST_ID, TIME_ID, QUANTITY_SOLD)
SELECT S.PROD_ID, S.CUST_ID, W.ID_WAKTU, S.QUANTITY_SOLD
FROM SALES S
LEFT JOIN WAKTU_NEW W ON S.TIME_ID = W.WAKTU;

-- INSERT KE PRODUK
INSERT INTO PRODUK
SELECT PROD_ID, PROD_NAME, P.PROD_SUBCATEGORY
FROM PRODUCTS;

-- INSERT KE PELANGGAN
INSERT INTO PELANGGAN
SELECT CUST_ID, CONCAT(CONCAT(CUST_FIRST_NAME, ' '), CUST_LAST_NAME), CUST_STREET_ADDRESS, CUST_CITY
FROM CUSTOMERS;

-- INSERT KE TABEL PENJUALAN
INSERT INTO PENJUALAN
SELECT S.PROD_ID, C.CUST_ID, S.TIME_ID, S.QUANTITY_SOLD
FROM SALES_NEW S
LEFT JOIN PRODUCTS P ON S.PROD_ID = P.PROD_ID
LEFT JOIN CUSTOMERS C ON S.CUST_ID = C.CUST_ID;

-- UJI COBA
SELECT PJ.NO_PRODUK, PJ.NO_PELANGGAN, PJ.NO_WAKTU, PJ.JUMLAH_PENJUALAN
FROM PENJUALAN PJ
LEFT JOIN PRODUK P ON PJ.NO_PRODUK = P.NO_PRODUK
LEFT JOIN PELANGGAN C ON PJ.NO_PELANGGAN = C.NO_PELANGGAN
LEFT JOIN WAKTU W ON PJ.NO_WAKTU = W.NO_WAKTU;

SELECT PJ.NO_PRODUK, PJ.NO_PELANGGAN, PJ.NO_WAKTU, PJ.JUMLAH_PENJUALAN
FROM PENJUALAN PJ, PRODUK P, PELANGGAN C, WAKTU W
WHERE PJ.NO_PRODUK = P.NO_PRODUK AND
    PJ.NO_PELANGGAN = C.NO_PELANGGAN AND
    PJ.NO_WAKTU = W.NO_WAKTU;