--------------------------------------------------------
--  File created - Monday-December-11-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_JUAL_BANTUAN
--------------------------------------------------------

  CREATE TABLE "FPM"."T_JUAL_BANTUAN" 
   (	"ID_BARANG" NUMBER(10,0), 
	"ID_CUST" NUMBER(10,0), 
	"TGL" NUMBER, 
	"TOTAL" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FPM" ;
--------------------------------------------------------
--  DDL for Table WAKTU_NEW
--------------------------------------------------------

  CREATE TABLE "FPM"."WAKTU_NEW" 
   (	"ID_WAKTU" NUMBER(10,0), 
	"WAKTU" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FPM" ;
--------------------------------------------------------
--  DDL for Index WAKTU_NEW_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FPM"."WAKTU_NEW_PK" ON "FPM"."WAKTU_NEW" ("ID_WAKTU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FPM" ;
--------------------------------------------------------
--  Constraints for Table WAKTU_NEW
--------------------------------------------------------

  ALTER TABLE "FPM"."WAKTU_NEW" ADD CONSTRAINT "WAKTU_NEW_PK" PRIMARY KEY ("ID_WAKTU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FPM"  ENABLE;
  ALTER TABLE "FPM"."WAKTU_NEW" MODIFY ("ID_WAKTU" NOT NULL ENABLE);
