INSERT INTO t_jns_brg (id, jenis) VALUES("AGA", "AGANOL");
INSERT INTO t_jns_brg (id, jenis) VALUES("ATOM", "Atom");
INSERT INTO t_jns_brg (id, jenis) VALUES("BALSEM", "Balsem");
INSERT INTO t_jns_brg (id, jenis) VALUES("BEDAK", "Bedak");
INSERT INTO t_jns_brg (id, jenis) VALUES("BTR", "BATERAI");
INSERT INTO t_jns_brg (id, jenis) VALUES("CB", "Cotton Buds");
INSERT INTO t_jns_brg (id, jenis) VALUES("CHARM", "CHARM");
INSERT INTO t_jns_brg (id, jenis) VALUES("CHIKI", "CHIKI");
INSERT INTO t_jns_brg (id, jenis) VALUES("CKL", "Cokelat");
INSERT INTO t_jns_brg (id, jenis) VALUES("CONE", "ZUPERCONE");
INSERT INTO t_jns_brg (id, jenis) VALUES("DE", "DEE-DEE");
INSERT INTO t_jns_brg (id, jenis) VALUES("DIAPER", "Baby Diaper");
INSERT INTO t_jns_brg (id, jenis) VALUES("DOT", "Dot Bayi");
INSERT INTO t_jns_brg (id, jenis) VALUES("DR", "DR.P");
INSERT INTO t_jns_brg (id, jenis) VALUES("EMAS", "EMAS");
INSERT INTO t_jns_brg (id, jenis) VALUES("EQ", "EQ");
INSERT INTO t_jns_brg (id, jenis) VALUES("HWI", "HAWAI");
INSERT INTO t_jns_brg (id, jenis) VALUES("JELY", "JELY");
INSERT INTO t_jns_brg (id, jenis) VALUES("KOLA", "Kola Finto");
INSERT INTO t_jns_brg (id, jenis) VALUES("KULIT", "Kulit");
INSERT INTO t_jns_brg (id, jenis) VALUES("M", "MIE");
INSERT INTO t_jns_brg (id, jenis) VALUES("MANILA", "MANILA");
INSERT INTO t_jns_brg (id, jenis) VALUES("MR", "MR BROLLY");
INSERT INTO t_jns_brg (id, jenis) VALUES("MRG", "Margarine");
INSERT INTO t_jns_brg (id, jenis) VALUES("NUT", "SUPERNUT");
INSERT INTO t_jns_brg (id, jenis) VALUES("OBAT", "Obat Nyamuk");
INSERT INTO t_jns_brg (id, jenis) VALUES("PERAK", "PERAK");
INSERT INTO t_jns_brg (id, jenis) VALUES("PERMEN", "PERMEN");
INSERT INTO t_jns_brg (id, jenis) VALUES("PIL", "PILUS");
INSERT INTO t_jns_brg (id, jenis) VALUES("POR", "PORSTEX");
INSERT INTO t_jns_brg (id, jenis) VALUES("PRG", "Piringan Kertas");
INSERT INTO t_jns_brg (id, jenis) VALUES("SBN", "Sabun");
INSERT INTO t_jns_brg (id, jenis) VALUES("SEA", "SEALER");
INSERT INTO t_jns_brg (id, jenis) VALUES("SEMIR", "Semir");
INSERT INTO t_jns_brg (id, jenis) VALUES("SIKAT", "Sikat");
INSERT INTO t_jns_brg (id, jenis) VALUES("SS", "SUSU");
INSERT INTO t_jns_brg (id, jenis) VALUES("SYRUP", "Syrup");
INSERT INTO t_jns_brg (id, jenis) VALUES("TS", "Tissue");
INSERT INTO t_jns_brg (id, jenis) VALUES("WFR", "WAFER");
INSERT INTO t_jns_brg (id, jenis) VALUES("WIP", "WIPES");
INSERT INTO t_jns_brg (id, jenis) VALUES("YR", "YURI");